#!/usr/bin/env bash

## Copyright (C) 2020-2024 Aditya Shakya <adi1090x@gmail.com>

# Import Current Theme

RASI="$cd ~/.config/polybar/rofi/launcher.rasi"

# Run
rofi \
    -show drun \
	-kb-cancel Escape \
	-theme ${RASI}
