#!/usr/bin/env bash

## Copyright (C) 2020-2024 Aditya Shakya <adi1090x@gmail.com>

# Import Current Theme

RASI="$cd ~/.config/polybar/rofi/runner.rasi"

# Run
rofi \
    -show run \
	-theme ${RASI}
